# Machine Learning

## Types

1. Supervised learning - regression & classification
2. Unsupervised learning - assosciation and clustering
3. reinforcement lerrning - reward points

## Python Packages

#### NUMPY

Numpy for single and multi dimensional array operations

In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6],[1,2,3]])
b = np.array([[1,2,3],[4,5,6],[1,2,3]])
print(np.multiply(a, b))

[[ 1  4  9]
 [16 25 36]
 [ 1  4  9]]


#### PANDAS

 Pandas is used for data manipulation and analysis

##### series

In [4]:
import pandas as pd
s = pd.Series([3, -5, 7, 4],  index=['a',  'b',  'c',  'd'])
print(s)

a    3
b   -5
c    7
d    4
dtype: int64


Data Frames

In [5]:
import pandas as pd
data = {'Country': ['Belgium',  'India',  'Brazil'],

'Capital': ['Brussels',  'New Delhi',  'Brasilia'],

'Population': [11190846, 1303171035, 207847528]}
df = pd.DataFrame(data,columns=['Country',  'Capital',  'Population'])
print(df)

Country    Capital  Population
0  Belgium   Brussels    11190846
1    India  New Delhi  1303171035
2   Brazil   Brasilia   207847528


#### MATPLOTLIB

#### SEABORN

#### SCIKIT_LEARN

#### TENSORFLOW

#### KERAS